spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/house
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    static-path-pattern: /**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
    #配置Mybatis的信息
    #spring集成Mybatis环境
    #pojo别名扫描包
mybatis:
  type-aliases-package: cn.beizhen.entity
  #加载Mybatis映射文件
  mapper-locations: classpath:cn.beizhen.mapper/*Mapper.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

